name: task_manager
description: A Flutter Task Manager app using your API (auth, tasks, dashboard, wizard).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management & navigation
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1
  go_router: ^14.2.0

  # Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # Models & JSON
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Storage & security
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.5.3
  path_provider: ^2.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Connectivity
  connectivity_plus: ^6.1.0

  # UI/UX
  flex_color_scheme: ^7.3.1
  intl: ^0.20.0
  easy_localization: ^3.0.5
  fl_chart: ^0.69.0
  lottie: ^3.1.2
  rive: ^0.13.7
  shimmer: ^3.0.0

  # Device info (useful later)
  device_info_plus: ^11.1.0
  package_info_plus: ^8.0.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - l10n/
